/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.interfazgrafica;

import controlador.controller;
import exception.CommandExecuteException;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author mario
 */
public class Paneldecontrol extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Panedecontrol
     */
    
    private JFileChooser fc;
    private controller ctr;
    
    public Paneldecontrol(controller c) {
        ctr = c;
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	fc = new JFileChooser();
		fc.setCurrentDirectory(new File("/src"));

        jButton1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton7 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/interfazgrafica/guardar.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/interfazgrafica/open.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(filler1);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/interfazgrafica/exit.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit(evt);
            }
        });
        jToolBar1.add(jButton7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        String n = JOptionPane.showInputDialog((Frame) SwingUtilities.getWindowAncestor(this), "Nombre del archivo para guardar", "save_01");
        if(n != null) {
            try {
				ctr.guardar(n);
			} catch (IOException | CommandExecuteException e) {
				e.printStackTrace();
			}
        }
    }//GEN-LAST:event_guardar

    private void cargar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar
        int valor = fc.showOpenDialog(this.getParent());
		
	if(valor == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            try {
                ctr.cargar(f.getName().split(".txt")[0]);
            } catch (CommandExecuteException | IOException ex) {
            	JOptionPane.showMessageDialog((Frame) SwingUtilities.getWindowAncestor(this), ex.getLocalizedMessage());
            }
	}
    }//GEN-LAST:event_cargar

    private void exit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit
        int n = JOptionPane.showOptionDialog((Frame) SwingUtilities.getWindowAncestor(this), 
		"You sure you wanna quit?", "Quit",  JOptionPane.YES_NO_OPTION, 
		JOptionPane.QUESTION_MESSAGE, null, null , null);
		
	if(n == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exit


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        fc = new JFileChooser();
	fc.setCurrentDirectory(new File("saves/"));
    }
}
